#!/bin/bash -e

echo Setting credentials to $USERNAME:$PASSWORD
PASSWORD=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)
userdel www-data
useradd --shell /bin/sh --create-home --password -u 33 -g 33 $PASSWORD $USERNAME
exec proftpd --nodaemon
