#!/bin/bash -e

echo Setting credentials to $USERNAME:$PASSWORD
PASSWORD=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)
userdel www-data
groupadd --gid 33 $USERNAME
useradd --shell /bin/sh --create-home --uid 33 --gid 33 --password $PASSWORD $USERNAME
exec proftpd --nodaemon
